services:
  redis:
    image: redis
    container_name: 'redis'
    ports:
      - 6379:6379
    expose:
      - 6379

  ai_container:
    image: ai_root
    build:
      context: .
      dockerfile: ai.Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - redis