const tags = [
    "Male",
    "Female",
    "Baby",
    "Child",
    "Teenager",
    "Young Adult",
    "Adult",
    "Elder",
    "Fitness and Wellness",
    "Tech and Gadgets",
    "Fashion and Accessories",
    "Books and Learning",
    "Travel and Adventure",
    "Food and Cooking",
    "Arts and Crafts",
    "Music and Entertainment",
    "Outdoor and Nature",
    "Beauty and Self-care",
    "Home and Decor",
    "Sports and Hobbies",
    "Pets and Animal Lovers",
    "Art and Culture",
    "Social Impact and Charity",
    "Spirituality",
    "Cars and Automotive",
    "Classic and Timeless",
    "Comfortable Yet Stylish",
    "Collectibles",
    "Science and Learning",
    "Premium Brands",
    "Minimalistic",
    "Practical",
    "Chill",
    "Bougie",
    "Birthdays",
    "Anniversaries",
    "Holidays",
    "Promotions and Achievements",
    "Graduations",
    "Valentine's Day",
    "Appreciation",
    "Get Well Soon",
    "Thank You Gifts",
    "Apologies",
]

module.exports = tags